id: org.davidedmundson.kiot
branch: master
runtime: org.kde.Platform
runtime-version: "6.10" # don't forget to change QtMqtt
sdk: org.kde.Sdk
command: kiot
tags:
  - nightly
desktop-file-name-suffix: " (Nightly)"
finish-args:
  - "--share=ipc"
  - "--share=network"
  - "--device=all"
  - "--socket=wayland"
  - "--socket=fallback-x11"
  - "--socket=session-bus"
  - "--socket=system-bus"
  - "--socket=pulseaudio"
  - "--filesystem=home:ro"
  - "--filesystem=xdg-config/kiotrc"
#Accent colour
  - "--filesystem=xdg-config/kdeglobals:ro"  
#Docker
  - "--filesystem=/run/docker.sock"
#SystemD
  - "--talk-name=org.freedesktop.systemd1"
#Notification integration i think
  - "--talk-name=org.kde.StatusNotifierWatcher"
  - "--own-name=org.kde.StatusNotifierItem-2-2"
#Kwin and active window integration
  - "--talk-name=org.kde.KWin"
#BLuetooth integration
  - "--talk-name=org.bluez"
  - "--talk-name=org.freedesktop.Flatpak"
#mpris
  - "--talk-name=org.mpris.MediaPlayer2"
  - "--talk-name=org.mpris.MediaPlayer2.*"

modules:
  - name: extra-cmake-modules
    buildsystem: cmake-ninja
    sources:
      - type: git
        url: https://invent.kde.org/frameworks/extra-cmake-modules
        tag: v6.30.0
        commit: 68483132b87f4d7b953aec94ef51d1234d41f937

  - name: qtmqtt
    buildsystem: cmake-ninja
    sources:
      - type: git
        url: https://github.com/qt/qtmqtt.git
        tag: 6.10.0
        commit: d18c7571f295cd17e32ca084e8b05c50f21feba0

  - name: pulseaudio-qt
    buildsystem: cmake-ninja
    sources:
      - type: git
        url: https://invent.kde.org/libraries/pulseaudio-qt
        tag: v1.8.1
        commit: 10786fe31e640858f4f5db5366aed9c56d77bfab

  - name: bluez-qt
    buildsystem: cmake-ninja
    sources:
      - type: git
        url: https://invent.kde.org/frameworks/bluez-qt
        tag: v6.30.0
        commit: 3f4f7ee54d560b6e46b84bc8467048d318f58afa

  - name: kiot
    buildsystem: cmake-ninja
    sources:
      - type: dir
        path: "."
    config-opts:
      - -DBUILD_FLATPAK=ON