id: org.davidedmundson.kiot
branch: master
runtime: org.kde.Platform
runtime-version: "6.10" # don't forget to change QtMqtt
sdk: org.kde.Sdk
command: kiot
tags:
  - nightly
desktop-file-name-suffix: " (Nightly)"
finish-args:
  - "--share=ipc"
  - "--share=network"
  - "--device=all"
  - "--socket=wayland"
  - "--socket=fallback-x11"
  - "--socket=session-bus"
  - "--socket=system-bus"

  - "--filesystem=home:ro"
  - "--filesystem=xdg-config/kiotrc"
  - "--talk-name=org.kde.StatusNotifierWatcher"
  - "--own-name=org.kde.StatusNotifierItem-2-2"
  - "--talk-name=org.kde.KWin"


modules:
  - name: extra-cmake-modules
    buildsystem: cmake-ninja
    sources:
      - type: git
        url: https://invent.kde.org/frameworks/extra-cmake-modules
        tag: v6.21.0

  - name: qtmqtt
    buildsystem: cmake-ninja
    sources:
      - type: git
        url: https://github.com/qt/qtmqtt.git
        tag: 6.10.0

  - name: pulseaudio-qt
    buildsystem: cmake-ninja
    sources:
      - type: git
        url: https://invent.kde.org/libraries/pulseaudio-qt
        tag: v1.7.0

  - name: bluez-qt
    buildsystem: cmake-ninja
    sources:
      - type: git
        url: https://invent.kde.org/frameworks/bluez-qt
        tag: v6.21.0

  - name: kiot
    buildsystem: cmake-ninja
    sources:
      - type: dir
        path: "."
