id: org.davidedmundson.kiot
branch: master
runtime: org.kde.Platform
runtime-version: "6.11" # don't forget to change QtMqtt
sdk: org.kde.Sdk
command: kiot
tags:
  - nightly
desktop-file-name-suffix: " (Nightly)"

# FOr testing with applauncher support
#environment:
#  XDG_DATA_DIRS: "/app/share:/usr/share:/usr/locale/share:/run/host/usr/share:/run/host/var/lib/flatpak/exports/share:$XDG_DATA_DIRS"

finish-args:
  - "--share=ipc"
  - "--share=network"
  - "--device=all"
  - "--socket=wayland"
  - "--socket=fallback-x11"
  - "--socket=session-bus"
  - "--socket=system-bus"
  - "--socket=pulseaudio"

  - "--filesystem=xdg-data/Steam:ro"          # GameLauncher For Steam
  - "--filesystem=xdg-data/lutris:ro"         # GameLauncher For Lutris
  - "--filesystem=xdg-config/heroic:ro"       # GameLauncher for Heroic
  - "--filesystem=xdg-config/kdeglobals:ro"   #Accent colour
  - "--filesystem=/run/docker.sock"           #Docker
  - "--talk-name=org.freedesktop.systemd1"    #SystemD
  - "--talk-name=org.kde.StatusNotifierWatcher" #For notifications?
  - "--own-name=org.kde.StatusNotifierItem-2-2" #For notifications?
  - "--talk-name=org.kde.KWin"                #Kwin and active window integration
  - "--talk-name=org.bluez"                   #BLuetooth integration
  - "--talk-name=org.freedesktop.Flatpak"
  - "--talk-name=org.kde.kglobalaccel"        #Shortcuts integration
  - "--talk-name=org.mpris.MediaPlayer2"      #mpris
  - "--talk-name=org.mpris.MediaPlayer2.*"    #mpris
  - "--talk-name=org.freedesktop.portal.*"    #Portal used in autostartup with background manager

modules:
  - name: extra-cmake-modules
    buildsystem: cmake-ninja
    sources:
      - type: git
        url: https://invent.kde.org/frameworks/extra-cmake-modules
        tag: v6.30.0
        commit: 68483132b87f4d7b953aec94ef51d1234d41f937

  - name: qtmqtt
    buildsystem: cmake-ninja
    sources:
      - type: git
        url: https://github.com/qt/qtmqtt.git
        tag: 6.11.2
        commit: 12144d369e4670291a80f8c7c6a775ab5103e391

  - name: pulseaudio-qt
    buildsystem: cmake-ninja
    sources:
      - type: git
        url: https://invent.kde.org/libraries/pulseaudio-qt
        tag: v1.8.1
        commit: 10786fe31e640858f4f5db5366aed9c56d77bfab

  - name: bluez-qt
    buildsystem: cmake-ninja
    sources:
      - type: git
        url: https://invent.kde.org/frameworks/bluez-qt
        tag: v6.30.0
        commit: 3f4f7ee54d560b6e46b84bc8467048d318f58afa

  - name: kiot
    buildsystem: cmake-ninja
    sources:
      - type: dir
        path: "."
    config-opts:
      - -DBUILD_FLATPAK=ON