[Scripts][display_philipsphilipsftv_primary]
Name=Set PHILIPS Philips FTV as Primary
Exec=kscreen-doctor output.DP-3.primary
Icon=mdi:monitor

[Scripts][display_philipsphilipsftv_enable]
Name=Set PHILIPS Philips FTV as Enabled
Exec=kscreen-doctor output.DP-3.enable
Icon=mdi:monitor

[Scripts][display_philipsphilipsftv_disable]
Name=Set PHILIPS Philips FTV as Disabled
Exec=kscreen-doctor output.DP-3.disable
Icon=mdi:monitor

[Scripts][display_philipsphilipsftv_rotate_left]
Name=Rotate PHILIPS Philips FTV to the left
Exec=kscreen-doctor output.DP-3.rotation.left
Icon=mdi:monitor

[Scripts][display_philipsphilipsftv_rotate_right]
Name=Rotate PHILIPS Philips FTV to the right
Exec=kscreen-doctor output.DP-3.rotation.right
Icon=mdi:monitor

[Scripts][display_philipsphilipsftv_hdr_enable]
Name=HDR PHILIPS Philips FTV Enable
Exec=kscreen-doctor output.DP-3.hdr.enable
Icon=mdi:monitor

[Scripts][display_philipsphilipsftv_hdr_disable]
Name=HDR PHILIPS Philips FTV Disable
Exec=kscreen-doctor output.DP-3.hdr.disable
Icon=mdi:monitor

[Scripts][display_hytey70ti_primary]
Name=Set HYTE Y70ti as Primary
Exec=kscreen-doctor output.DP-1.primary
Icon=mdi:monitor

[Scripts][display_hytey70ti_enable]
Name=Set HYTE Y70ti as Enabled
Exec=kscreen-doctor output.DP-1.enable
Icon=mdi:monitor

[Scripts][display_hytey70ti_disable]
Name=Set HYTE Y70ti as Disabled
Exec=kscreen-doctor output.DP-1.disable
Icon=mdi:monitor

[Scripts][display_hytey70ti_rotate_left]
Name=Rotate HYTE Y70ti to the left
Exec=kscreen-doctor output.DP-1.rotation.left
Icon=mdi:monitor

[Scripts][display_hytey70ti_rotate_right]
Name=Rotate HYTE Y70ti to the right
Exec=kscreen-doctor output.DP-1.rotation.right
Icon=mdi:monitor

[Scripts][display_hytey70ti_hdr_enable]
Name=HDR HYTE Y70ti Enable
Exec=kscreen-doctor output.DP-1.hdr.enable
Icon=mdi:monitor

[Scripts][display_hytey70ti_hdr_disable]
Name=HDR HYTE Y70ti Disable
Exec=kscreen-doctor output.DP-1.hdr.disable
Icon=mdi:monitor

