name: Docker Build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the Docker image using the Dockerfile
      - name: Build Docker Image
        run: |
          docker build --target runtime -t kiot:latest .
